// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnOhyoSRkGrDslhubtOp3RqQ437W2XMvA',
    appId: '1:269775325253:web:17eab4c40d7eae6ddd7b2c',
    messagingSenderId: '269775325253',
    projectId: 'docu-tracker-ac4ea',
    authDomain: 'docu-tracker-ac4ea.firebaseapp.com',
    storageBucket: 'docu-tracker-ac4ea.firebasestorage.app',
    measurementId: 'G-LGHLEKMEWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk_uNzYOkczfFLODGHXAKGNR5XHHeNj-w',
    appId: '1:269775325253:android:c0e241b9c6908a22dd7b2c',
    messagingSenderId: '269775325253',
    projectId: 'docu-tracker-ac4ea',
    storageBucket: 'docu-tracker-ac4ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD8U2iebiX2NveizkM45w9Y_oHt2sN9b0',
    appId: '1:269775325253:ios:1aa5a72aeb99964fdd7b2c',
    messagingSenderId: '269775325253',
    projectId: 'docu-tracker-ac4ea',
    storageBucket: 'docu-tracker-ac4ea.firebasestorage.app',
    iosBundleId: 'com.cpdco.docutracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD8U2iebiX2NveizkM45w9Y_oHt2sN9b0',
    appId: '1:269775325253:ios:6d12f584ffcaeaf3dd7b2c',
    messagingSenderId: '269775325253',
    projectId: 'docu-tracker-ac4ea',
    storageBucket: 'docu-tracker-ac4ea.firebasestorage.app',
    iosBundleId: 'com.example.documentTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnOhyoSRkGrDslhubtOp3RqQ437W2XMvA',
    appId: '1:269775325253:web:212188e9de9d9ce0dd7b2c',
    messagingSenderId: '269775325253',
    projectId: 'docu-tracker-ac4ea',
    authDomain: 'docu-tracker-ac4ea.firebaseapp.com',
    storageBucket: 'docu-tracker-ac4ea.firebasestorage.app',
    measurementId: 'G-KNY128GTBL',
  );
}
