name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Create Supabase config
        run: |
          echo "class SupabaseConfig {
            static const String supabaseUrl = String.fromEnvironment('SUPABASE_URL');
            static const String supabaseAnonKey = String.fromEnvironment('SUPABASE_ANON_KEY');
          }
          
      - name: Create Auth config
        run: |
          echo "const String developerPassword = String.fromEnvironment('DEVELOPER_PASSWORD');" > lib/config/auth_config.dart
           
      - name: Build Flutter web
        run: flutter build web --release --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} --dart-define=SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} --dart-define=DEVELOPER_PASSWORD=${{ secrets.DEVELOPER_PASSWORD }}

      - name: Set up Firebase credentials
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $HOME/firebase.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase.json" >> $GITHUB_ENV

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project docu-tracker-ac4ea
